# Generated by Django 5.1.2 on 2024-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
